# Generated by Django 5.1.6 on 2025-06-07 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=4)),
                ("history_title", models.CharField(max_length=255)),
                ("history_text", models.TextField()),
                ("mission", models.TextField(default=None)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="about_images/"),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, verbose_name="Slug")),
                ("author", models.CharField(max_length=100, verbose_name="Auteur")),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Catégorie"),
                ),
                ("content", models.TextField(verbose_name="Contenu (Markdown)")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de publication"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConversionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projects_completed",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Nombre total de projets terminés",
                        verbose_name="Projets Réalisés",
                    ),
                ),
                (
                    "client_satisfaction",
                    models.PositiveIntegerField(
                        default=98,
                        help_text="Pourcentage de satisfaction client",
                        verbose_name="Satisfaction Client (%)",
                    ),
                ),
                (
                    "response_time_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Temps de réponse maximum en heures",
                        verbose_name="Temps de Réponse (heures)",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Nombre d'années d'expertise",
                        verbose_name="Années d'Expérience",
                    ),
                ),
                (
                    "active_clients",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Nombre de clients actuellement accompagnés",
                        verbose_name="Clients Actifs",
                    ),
                ),
                (
                    "technologies_mastered",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Nombre de technologies et frameworks maîtrisés",
                        verbose_name="Technologies Maîtrisées",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Utiliser ces statistiques sur le site",
                        verbose_name="Actif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques de Conversion",
                "verbose_name_plural": "Statistiques de Conversion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="clients/")),
                (
                    "secteur",
                    models.CharField(
                        choices=[
                            ("tech", "Technologie"),
                            ("finance", "Finance"),
                            ("sante", "Santé"),
                            ("ecommerce", "E-commerce"),
                            ("industrie", "Industrie"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("gitHub", models.URLField(blank=True, null=True)),
                ("medium", models.URLField(blank=True, null=True)),
                ("position", models.CharField(max_length=150)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("location", models.CharField(max_length=100)),
                ("about", models.TextField(max_length=1200, null=True)),
                (
                    "cv",
                    models.FileField(blank=True, null=True, upload_to="KOTO/media/cvs"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeroCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hero-carousel/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Entreprise"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Type de Projet",
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Budget"
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Délai"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contact_form", "Formulaire de Contact"),
                            ("newsletter", "Newsletter"),
                            ("free_consultation", "Consultation Gratuite"),
                            ("pricing_page", "Page Tarifs"),
                            ("service_page", "Page Service"),
                            ("blog", "Blog"),
                            ("other", "Autre"),
                        ],
                        default="contact_form",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("contacted", "Contacté"),
                            ("qualified", "Qualifié"),
                            ("proposal_sent", "Devis Envoyé"),
                            ("won", "Gagné"),
                            ("lost", "Perdu"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="Urgent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(unique=True, verbose_name="Numéro"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Pratique",
                "verbose_name_plural": "Nos Pratiques",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom du Plan")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professionnel"),
                            ("enterprise", "Entreprise"),
                            ("custom", "Sur Mesure"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix en euros",
                        max_digits=10,
                        verbose_name="Prix (€)",
                    ),
                ),
                (
                    "price_period",
                    models.CharField(
                        default="projet",
                        help_text="Ex: projet, mois, an",
                        max_length=50,
                        verbose_name="Période",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description du plan")),
                (
                    "features",
                    models.TextField(
                        help_text="Une fonctionnalité par ligne",
                        verbose_name="Fonctionnalités",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mettre en avant ce plan",
                        verbose_name="Plan Populaire",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Démarrer",
                        max_length=100,
                        verbose_name="Texte du bouton",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plan Tarifaire",
                "verbose_name_plural": "Plans Tarifaires",
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du service"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="Une phrase percutante qui résume le service.",
                        max_length=255,
                        null=True,
                        verbose_name="Description courte",
                    ),
                ),
                (
                    "detailed_description",
                    models.TextField(
                        help_text="Explique en quoi ce service est utile et ses avantages.",
                        null=True,
                        verbose_name="Description complète",
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        help_text="Liste des bénéfices concrets, séparés par des virgules.",
                        null=True,
                        verbose_name="Avantages clés",
                    ),
                ),
                (
                    "target_clients",
                    models.CharField(
                        help_text="Ex: Startups, PME, Grandes entreprises, Freelancers...",
                        max_length=255,
                        null=True,
                        verbose_name="Public cible",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="services/",
                        verbose_name="Image illustrant le service",
                    ),
                ),
                (
                    "call_to_action",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Contactez-nous pour une consultation gratuite",
                        max_length=255,
                        null=True,
                        verbose_name="Texte d'appel à l'action",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoftSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du client"),
                ),
                ("feedback", models.TextField(verbose_name="Témoignage")),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Entreprise (optionnel)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Approuvé par l'admin"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(blank=True, max_length=100, null=True)),
                ("specialty", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(max_length=500)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="nene.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("platform", models.CharField(max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="nene.employee",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="certifications", to="nene.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="softSkills",
            field=models.ManyToManyField(
                related_name="employees", to="nene.softskills"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("demo", models.URLField(blank=True, null=True)),
                ("depot", models.URLField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="nene.employee",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="projects", to="nene.technology"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(max_length=1200)),
                ("city", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="nene.employee",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="experiences", to="nene.technology"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
