# Generated by Django 5.1.6 on 2025-06-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
