# Generated by Django 5.1.6 on 2025-02-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Slug"),
        ),
    ]
