# Generated by Django 5.1.6 on 2025-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0002_alter_testimonial_is_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
        migrations.AddField(
            model_name="testimonial",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Poste occupé"
            ),
        ),
    ]
