# Generated by Django 5.1.6 on 2025-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0003_alter_testimonial_options_testimonial_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Brouillon"),
        ),
        migrations.AddField(
            model_name="article",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière modification"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Description pour les moteurs de recherche",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="read_time",
            field=models.PositiveIntegerField(
                default=0, help_text="Temps de lecture estimé en minutes"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Mettre en avant ce projet"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Brouillon"),
        ),
        migrations.AddField(
            model_name="project",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.CharField(
                blank=True, help_text="Brève description du projet", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
