# Generated by Django 5.1.6 on 2025-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0003_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="notebook",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notebooks/",
                verbose_name="Notebook (optionnel)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Contenu (Markdown)"),
        ),
    ]
