# Generated by Django 5.1.6 on 2025-02-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0004_article_notebook_alter_article_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="notebook",
        ),
    ]
