# Generated by Django 5.1.6 on 2025-06-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0004_article_is_draft_article_last_modified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_draft",
        ),
        migrations.RemoveField(
            model_name="article",
            name="last_modified",
        ),
        migrations.RemoveField(
            model_name="article",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="article",
            name="read_time",
        ),
        migrations.RemoveField(
            model_name="project",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_draft",
        ),
        migrations.RemoveField(
            model_name="project",
            name="last_modified",
        ),
        migrations.RemoveField(
            model_name="project",
            name="short_description",
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
