# Generated by Django 5.1.6 on 2025-06-09 20:52

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0006_category_blogpost_codesnippet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="codesnippet",
            name="blog_post",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="codesnippet",
            options={
                "ordering": ["id"],
                "verbose_name": "Extrait de code",
                "verbose_name_plural": "Extraits de code",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-date"],
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Description pour le SEO",
                max_length=160,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("draft", "Brouillon"), ("published", "Publié")],
                default="draft",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="codesnippet",
            name="article",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_snippets",
                to="nene.article",
                verbose_name="Article",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Description pour le SEO",
                max_length=160,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("in_progress", "En cours"),
                    ("completed", "Terminé"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Contenu"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/",
                verbose_name="Image à la une",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="code",
            field=models.TextField(verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("html", "HTML"),
                    ("css", "CSS"),
                    ("php", "PHP"),
                    ("java", "Java"),
                    ("sql", "SQL"),
                    ("bash", "Bash"),
                    ("other", "Autre"),
                ],
                max_length=20,
                verbose_name="Langage",
            ),
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="project",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="demo",
            field=models.URLField(
                blank=True, null=True, verbose_name="Lien de démonstration"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="depot",
            field=models.URLField(blank=True, null=True, verbose_name="Dépôt de code"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="nene.employee",
                verbose_name="Employé",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/",
                verbose_name="Image principale",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                related_name="projects",
                to="nene.technology",
                verbose_name="Technologies",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
