# Generated by Django 5.1.6 on 2025-02-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0007_employee_slug_project_slug_alter_education_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="softSkills",
            field=models.ManyToManyField(
                related_name="employees", to="nene.softskills"
            ),
        ),
    ]
