# Generated by Django 5.1.6 on 2025-02-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0009_employee_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gitHub",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="medium",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="demo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="depot",
            field=models.URLField(blank=True, null=True),
        ),
    ]
