# Generated by Django 5.1.6 on 2025-02-22 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0010_employee_github_employee_medium_project_demo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
