# Generated by Django 5.1.6 on 2025-02-22 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0012_skill_certification"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
