# Generated by Django 5.1.6 on 2025-02-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0013_certification_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre principal"),
                ),
                ("year", models.CharField(max_length=4, verbose_name="Année")),
                (
                    "history_title",
                    models.CharField(
                        max_length=255, verbose_name="Titre de l'histoire"
                    ),
                ),
                ("history_text", models.TextField(verbose_name="Texte de l'histoire")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="about/", verbose_name="Image"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de la vidéo"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={"ordering": ["-date"]},
        ),
    ]
