# Generated by Django 5.1.6 on 2025-02-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0014_aboutsection_alter_certification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutsection",
            name="mission",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="aboutsection",
            name="history_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="aboutsection",
            name="history_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="aboutsection",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="about_images/"),
        ),
        migrations.AlterField(
            model_name="aboutsection",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="aboutsection",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutsection",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
