# Generated by Django 5.1.6 on 2025-02-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0015_aboutsection_mission_alter_aboutsection_history_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Numéro")),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Pratique",
                "verbose_name_plural": "Nos Pratiques",
                "ordering": ["number"],
            },
        ),
    ]
