app = "gabithex"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "KOTO.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/KOTO/staticfiles"
  url_prefix = "/static"

[deploy]
  release_command = "python KOTO/manage.py migrate" 