app = "mon-postgres"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PGDATA = "/data/postgres"

[mounts]
  source = "pg_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 5432
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"] 